variables:
  GIT_CLEAN_FLAGS: -ffdx
stages:
  - build
  - release

#Compilacion en linux, develop, tags y rama de test
build_linux:
  stage: build
  image: stateoftheartio/qt6:6.7-gcc-aqt
  tags:
    - ddm-linux-local
  rules:
    - if: '$CI_COMMIT_TAG =~ /-linux$/ || $CI_COMMIT_TAG =~ /-win$/'
      when: never
    - if: '$CI_COMMIT_BRANCH == "develop"'
    - if: '$CI_COMMIT_BRANCH == "test/yml-linux"'
    - if: '$CI_COMMIT_TAG'
  script:
    - echo "Preparando entorno de Linux instalando dependencias gráficas..."
    - sudo apt-get update -qq && sudo apt-get install -y libgl1-mesa-dev libglu1-mesa-dev
    - echo "Compilando versión RELEASE en Debian..."
    - mkdir -p build_linux
    - cd build_linux
    - qmake ../DDM.pro CONFIG+=release
    - make -j$(nproc)
  artifacts:
    name: "DDM-Linux-v$CI_COMMIT_TAG"
    paths:
      - build_linux/

#Release para linux
release_linux:
  stage: release
  image: registry.gitlab.com/gitlab-org/release-cli:latest
  tags:
    - ddm-linux-local
  rules:
    - if: '$CI_COMMIT_TAG =~ /-linux$/'
      when: never
    - if: '$CI_COMMIT_TAG'
  script:
    - echo "Generando Release para Linux directamente desde el comando..."
    - |
      release-cli create --name "DDM Linux $CI_COMMIT_TAG" \
        --description "Binarios oficiales para Linux Debian" \
        --tag-name "$CI_COMMIT_TAG-linux" \
        --assets-link "{\"name\":\"Descargar-DDM-Linux-Release\",\"url\":\"${CI_PROJECT_URL}/-/jobs/artifacts/${CI_COMMIT_TAG}/download?job=build_linux}"