name: Tests para DDM
on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]
jobs:
  build-linux:
    name: Compilar en Debian
    runs-on: ubuntu-latest
    container:
      image: debian:bookworm
    steps:
    - name: Instalar dependencias base
      run: |
        apt-get update -qq
        apt-get install -y sudo git curl libgl1-mesa-dev libglu1-mesa-dev build-essential

    - name: Descargar código
      uses: actions/checkout@v4

    - name: Instalar Qt para Linux (6.7.3)
      uses: jurplel/install-qt-action@v3
      with:
        version: '6.7.3'
        host: 'linux'
        target: 'desktop'

    - name: Compilar en Debian
      run: |
        mkdir build
        cd build
        qmake ../DDM.pro
        make -j$(nproc)

    - name: Subir Artefacto Linux
      uses: actions/upload-artifact@v4
      with:
        name: DDM-Linux-Debug
        path: build/
